### ISSUE TITLE
categories no open

### ISSUE THREAD

**Issue by msaulohenrique** [isfaaghyth/Wordpress-Reader-Android#1]
Hello good afternoon, I have been modifying their design for my blog, however the tab category categories, when I click on something, do not open a list of pertecente articles to it. You could check this?
I tried to include the author's name, only that is giving fatal error.
Comments about get by the name and email fields, and is working perfectly.

Congratulations on the project.

**Comment by isfaaghyth** [comment]
Hallo,
sorry for late response.
I will be rebuild for this project with a simple and clean code (with RxVolley and MVP Architecture).
so, please wait 😄
