### ISSUE TITLE
[Feature Request] Push notification when new article get published

### ISSUE THREAD

**Issue by suds7** [isfaaghyth/Wordpress-Reader-Android#2]
I'm trying to figure out way to get push notification when new article get published. Are you planning to add this feature in future?

Excellent project got to learn lots of things.

**Comment by isfaaghyth** [comment]
yes, of course.
you can use socket.io or firebase :) 
maybe, I will be add this feature for future. (using: firebase).

stay tune :)

**Comment by suds7** [comment]
Thanks
