### ISSUE TITLE
Screenshot is missing

### ISSUE THREAD

**Issue by agkarun** [isfaaghyth/Wordpress-Reader-Android#3]

**Comment by isfaaghyth** [comment]
I recommended you to follow this:
https://github.com/isfaaghyth/nfkita-mobile-1

- [x] clean code
- [x] rxjava, already!
- [x] used modern http library (retrofit)

**Comment by agkarun** [comment]
Thank you bui i need screenshot can u please mail me @ agkarun96@gmail.com

**Comment by isfaaghyth** [comment]
it's like that.

![image](https://user-images.githubusercontent.com/6775159/32335839-5cdc62c2-c020-11e7-8787-96d20128185a.png)

![image](https://user-images.githubusercontent.com/6775159/32335847-6165f416-c020-11e7-906c-18e040526518.png)

![image](https://user-images.githubusercontent.com/6775159/32335857-65fdf596-c020-11e7-9130-9f996544b06c.png)

![image](https://user-images.githubusercontent.com/6775159/32335864-6bfe8afa-c020-11e7-993c-bd3324276665.png)

![image](https://user-images.githubusercontent.com/6775159/32335880-728f6de4-c020-11e7-9244-0de8576b073b.png)

correct me if I wrong, and don't forget ti click star button 😄

**Comment by agkarun** [comment]
Of course this
